name: Construction d'un projet

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
    - name: Create folder
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sudo mkdir -p /opt/applications/sa
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Téléchargement des sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -Dmaven.tests.skip=true -B package --file pom.xml
    - name: rename jar file
      run: mv target/*.jar target/sa.jar
    - name: copy jar file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "target/*.jar"
        target: /opt/applications/sa

