name: Construction d'un projet

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:


jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
     - name: Create folder on remote VM
       uses: appleboy/ssh-action@v1.0.0
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: mkdir -p /opt/appllications/sa
  build:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
    - name: Téléchargement des sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml

    - name: Rename jar
      run: mv target/*.jar target/sa.jar

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "target/sa.jar"
        target: /opt/appllications/sa
  run script:
    name: run script
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Create folder on remote VM
       uses: appleboy/ssh-action@v1.0.0
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
            ln -sf /opt/appllications/sa/sa.jar /etc/init.d/sa
            service start sa
